apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
