apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: whatyousay
      type: string
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "$(params.whatyousay)"
