apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-buildah-express-pipeline-run-
  namespace: default
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: tekton-buildah-express-pipeline-74rk8
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim: # Affinity Assistant
        claimName: pipeline-pvc
