apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-eventlistener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: triggerbinding
      template:
        ref: triggertemplate
