apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding
spec:
  params:
    - name: giturl
      value: $(body.repository.clone_url)
    - name: gitrevision
      value: $(body.repository.default_branch)
